services:
  app:
    build:
      context: ./php
    container_name: manga_php
    working_dir: /var/www/html
    user: "501:20"
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: manga_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - manga_vol:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: manga_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  manga_vol:
